version: "3"
services:
  backend:
    image: 032068930732.dkr.ecr.eu-north-1.amazonaws.com/backend-app:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=threetier-db.cjg6iyecg00m.eu-north-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=Vasu0514
      - DB_NAME=threetierdb

  frontend:
    image: 032068930732.dkr.ecr.eu-north-1.amazonaws.com/frontend-app:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
