name: Artifact Practice

on:
  push:
    branches: [GH-Actions-Practice]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create a file
        run: echo "Hello from test job" > message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: message.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file

      - name: Show file contents
        run: cat message.txt
