name: Secrets and Variables

on:
 push:
  branches: [main]
 workflow_dispatch:

jobs:
 test:
  runs-on: ubuntu-latest
  env:
   APP_ENV: production
  steps:
   - name: show env variable
     run: echo "Environment is ${{ env.APP_ENV }}"
   - name: show secret
     run: echo "My secret is ${{ secrets.MY_SECRET }}"
   - name: show variable
     run: echo "My Var is ${{ vars.MY_VAR }}"
 
 deploy:
  runs-on: ubuntu-latest
  environment: production
  needs: [test]
  steps:
   - name: Printing environment variable at repo level
     run: echo " Variable is ${{ vars.MY_VAR }}"
