name: Test and Deploy

on:
  push:
    branches: [GH-Actions-Practice]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        run: actions/checkout@v4
      - name: Step 2 - Pretend test cases
        run: echo "Test cases Passed"

  deploy: 
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fake Deploy
        run: echo "Deployed successfully"
  
