name: Test and Deploy

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        run: echo "Checking out code"
      - name: Step 2 - Pretend test cases
        run: echo "Test cases Passed"

  deploy: 
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fake Deploy
        run: echo "Deployed successfully"
  
